name: Fetch Repository Details

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      pat_token:
        description: "Enter your Personal Access Token (PAT) for the second job"
        required: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  fetch-info:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        run: |
          echo "OWNER=infotechay" >> $GITHUB_ENV
          echo "REPO=gke-cicd" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Fetch Repository Branches
        run: |
          curl -X GET -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/$OWNER/$REPO/branches \
            > branches.json
          echo "Printing branches.json"
          cat branches.json

      - name: Fetch Repository Protection Rules
        run: |
          curl -X GET -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/$OWNER/$REPO/branches/main/protection \
            > protection_rules.json
          echo "Printing protection_rules.json"
          cat protection_rules.json

      - name: Fetch Repository Collaborators
        run: |
          curl -X GET -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/$OWNER/$REPO/collaborators \
            > collaborators.json
          echo "Printing collaborators.json"
          cat collaborators.json

      - name: Fetch Repository Teams
        run: |
          curl -X GET -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/$OWNER/$REPO/teams \
            > teams.json
          echo "Printing teams.json"
          cat teams.json

  list-environments:
    runs-on: ubuntu-latest
    needs: fetch-info
    steps:
      - name: Get User Input for PAT
        if: ${{ github.event.inputs.pat_token == null }}
        run: echo "PAT Token is missing! Please trigger manually with the PAT token."

      - name: List All Environments
        env:
          PAT_TOKEN: ${{ github.event.inputs.pat_token }}
          OWNER: infotechay
          REPO: gke-cicd
        run: |
          if [ -z "$PAT_TOKEN" ]; then
            echo "PAT Token is not provided. Exiting..."
            exit 1
          fi
          echo "Fetching all environments for repository: $REPO"
          ENVIRONMENTS=$(curl -s -H "Authorization: token $PAT_TOKEN" \
                            -H "Accept: application/vnd.github.v3+json" \
                            "https://api.github.com/repos/$OWNER/$REPO/environments" | jq -r '.environments[].name')
          echo "Environments: $ENVIRONMENTS"
